---
version: '3.4'
services:

  bootnode:
    build:
      context: besu/.
      args:
        BESU_VERSION: ${BESU_VERSION}
    image: quickstart/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    entrypoint: /opt/besu/bootnode_start.sh --network=dev --metrics-enabled --metrics-host=0.0.0.0 --metrics-port=9545 --host-whitelist=*
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}

  minernode:
    image: quickstart/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: ["--network=dev",
              "--miner-enabled",
              "--metrics-enabled",
              "--metrics-host=0.0.0.0",
              "--metrics-port=9545",
              "--miner-coinbase=${MINER_COINBASE}",
              "--host-whitelist=*"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
    depends_on:
      - bootnode

  node:
    image: quickstart/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: ["--network=dev",
              "--metrics-enabled",
              "--metrics-host=0.0.0.0",
              "--metrics-port=9545",
              "--host-whitelist=*"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
    depends_on:
      - bootnode

  rpcnode:
    image: quickstart/besu:${BESU_VERSION}
    command: ["--network=dev",
              "--rpc-http-enabled",
              "--rpc-http-host=0.0.0.0",
              "--rpc-http-port=8545",
              "--rpc-http-cors-origins=*",
              "--rpc-ws-enabled",
              "--rpc-ws-host=0.0.0.0",
              "--rpc-ws-port=8546",
              "--metrics-enabled",
              "--metrics-host=0.0.0.0",
              "--metrics-port=9545",
              "--graphql-http-enabled",
              "--graphql-http-host=0.0.0.0",
              "--graphql-http-port=8547",
              "--graphql-http-cors-origins=*",
              "--host-whitelist=*"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
    depends_on:
      - bootnode

  explorer:
    build: block-explorer-light/.
    image: "quickstart/block-explorer-light:${BESU_VERSION}"
    depends_on:
      - rpcnode
    ports:
      - "${EXPLORER_PORT_MAPPING:-0}:80"

  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=http://localhost:9090/prometheus
      - --web.route-prefix=/prometheus

  grafana:
    image: "grafana/grafana"
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana


volumes:
  public-keys:

  prometheus:

  grafana:

