version: '3.2'
services:
  bootnode:
    build:
      context: pantheon
      args:
        PANTHEON_VERSION: ${PANTHEON_VERSION}
    image: quickstart/pantheon:${PANTHEON_VERSION}-privacy
    environment:
      - PANTHEON_PUBLIC_KEY_DIRECTORY=${PANTHEON_PUBLIC_KEY_DIRECTORY}
    entrypoint: /opt/pantheon/bootnode_start.sh --network=dev
    volumes:
      - public-keys:${PANTHEON_PUBLIC_KEY_DIRECTORY}

  minernode:
    image: quickstart/pantheon:${PANTHEON_VERSION}-privacy
    environment:
      - PANTHEON_PUBLIC_KEY_DIRECTORY=${PANTHEON_PUBLIC_KEY_DIRECTORY}
    command: ["--network=dev",
              "--miner-enabled",
              "--miner-coinbase=${MINER_COINBASE}"]
    volumes:
      - public-keys:${PANTHEON_PUBLIC_KEY_DIRECTORY}
    depends_on:
      - bootnode

  orion1:
    build:
      context: orion
    image: quickstart/orion:${ORION_VERSION}
    entrypoint: /orion/build/bin/orion ${ORION_DATA_FOLDER1}/orion.conf
  orion2:
    image: quickstart/orion:${ORION_VERSION}
    entrypoint: /orion/build/bin/orion ${ORION_DATA_FOLDER2}/orion.conf
  orion3:
    image: quickstart/orion:${ORION_VERSION}
    entrypoint: /orion/build/bin/orion ${ORION_DATA_FOLDER3}/orion.conf

  node1:
    image: quickstart/pantheon:${PANTHEON_VERSION}-privacy
    environment:
      - PANTHEON_PUBLIC_KEY_DIRECTORY=${PANTHEON_PUBLIC_KEY_DIRECTORY}
    command: ["--network=dev",
              "--privacy-enabled=true",
              "--privacy-url=${ORION_URL1}",
              "--rpc-http-enabled",
              "--rpc-http-host=0.0.0.0",
              "--rpc-http-port=8545",
              "--rpc-http-cors-origins=*",
              "--rpc-ws-enabled",
              "--rpc-ws-host=0.0.0.0",
              "--rpc-ws-port=8546",
              "--rpc-http-api=EEA,WEB3,ETH,NET",
              "--host-whitelist=*"]
    volumes:
      - public-keys:${PANTHEON_PUBLIC_KEY_DIRECTORY}
      - ${PWD}/pantheon/data1:/var/lib/pantheon
      - ${PWD}/orion/orion1:/etc/pantheon
    depends_on:
      - bootnode
      - orion1
    ports:
      - 20000:8545
      - 20001:8546

  node2:
    image: quickstart/pantheon:${PANTHEON_VERSION}-privacy
    environment:
      - PANTHEON_PUBLIC_KEY_DIRECTORY=${PANTHEON_PUBLIC_KEY_DIRECTORY}
    command: ["--network=dev",
              "--privacy-enabled=true",
              "--privacy-url=${ORION_URL2}",
              "--rpc-http-enabled",
              "--rpc-http-host=0.0.0.0",
              "--rpc-http-port=8545",
              "--rpc-http-cors-origins=*",
              "--rpc-ws-enabled",
              "--rpc-ws-host=0.0.0.0",
              "--rpc-ws-port=8546",
              "--rpc-http-api=EEA,WEB3,ETH,NET",
              "--host-whitelist=*"]
    volumes:
      - public-keys:${PANTHEON_PUBLIC_KEY_DIRECTORY}
      - ${PWD}/pantheon/data2:/var/lib/pantheon
      - ${PWD}/orion/orion2:/etc/pantheon
    depends_on:
      - bootnode
      - orion2
    ports:
      - 20002:8545
      - 20003:8546
  node3:
    image: quickstart/pantheon:${PANTHEON_VERSION}-privacy
    environment:
      - PANTHEON_PUBLIC_KEY_DIRECTORY=${PANTHEON_PUBLIC_KEY_DIRECTORY}
    command: ["--network=dev",
              "--privacy-enabled=true",
              "--privacy-url=${ORION_URL3}",
              "--rpc-http-enabled",
              "--rpc-http-host=0.0.0.0",
              "--rpc-http-port=8545",
              "--rpc-http-cors-origins=*",
              "--rpc-ws-enabled",
              "--rpc-ws-host=0.0.0.0",
              "--rpc-ws-port=8546",
              "--rpc-http-api=EEA,WEB3,ETH,NET",
              "--host-whitelist=*"]
    volumes:
      - public-keys:${PANTHEON_PUBLIC_KEY_DIRECTORY}
      - ${PWD}/orion/orion3:/etc/pantheon
    depends_on:
      - bootnode
      - orion3
    ports:
      - 20004:8545
      - 20005:8546

  rpcnode:
    image: quickstart/pantheon:${PANTHEON_VERSION}-privacy
    command: ["--network=dev",
              "--rpc-http-enabled",
              "--rpc-http-host=0.0.0.0",
              "--rpc-http-port=8545",
              "--rpc-http-cors-origins=*",
              "--rpc-ws-enabled",
              "--rpc-ws-host=0.0.0.0",
              "--rpc-ws-port=8546",
              "--host-whitelist=*"]
    volumes:
      - public-keys:${PANTHEON_PUBLIC_KEY_DIRECTORY}
    depends_on:
      - bootnode
  explorer:
    build: ../block-explorer-light
    image: "quickstart/block-explorer-light:${PANTHEON_VERSION}"
    depends_on:
      - rpcnode
    ports:
      - "${EXPLORER_PORT_MAPPING:-}80"
volumes:
  public-keys:
